src/Entity/Wish.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WishRepository")
 */
class Wish
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $short_description;

    /**
     * @ORM\Column(type="integer")
     */
    private $value;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="wishes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getValue(): ?int
    {
        return $this->value;
    }

    public function setValue(int $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getUserId(): ?user
    {
        return $this->user_id;
    }

    public function setUser(?user $user) : self
    {

        $this->user = $user;

        return $this;
    }

}

src/Controller/HomepageController.php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\WishRepository;
use App\Entity\Wish;


class HomepageController extends AbstractController
{
    /**
     * @Route("/", name="/")
     */
    public function index(EntityManagerInterface $em)
    {

       $repository = $this->getDoctrine()->getRepository(Wish::class);
       $wishes = $repository->findAll();

        return $this->render('homepage/homepage.html.twig',[
            'wishes' => $wishes
        ]);
    }


}

templates/homepage/homepage.html.twig
{% extends "base.html.twig" %}
{% block body %}

    <div class="container">
        <div class="row">
            {% for wish in wishes %}

                <div class="card col-sm-3 m-2">
                    <img src="https://i.picsum.photos/id/486/100/100.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ wish.title }}</h5>
                        <p class="card-text">{{ wish.shortDescription }}</p>
                        <a href="#" class="btn btn-primary">Details</a>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>

{%  endblock %}